name: Publicar Studio

on:
  push:
    branches:
      - main
      - develop
  workflow_dispatch:

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # ==========================================
      #   DEPLOYS DA BRANCH MAIN (PRODUÇÃO)
      # ==========================================
      - name: Deploy Main
        if: github.ref == 'refs/heads/main'
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./studio  # Copia seus arquivos estáticos diretamente
          keep_files: true       # Impede que apague a pasta /dev

      # ==========================================
      #   DEPLOYS DA BRANCH DEVELOP (HOMOLOGAÇÃO)
      # ==========================================
      - name: Deploy Develop
        if: github.ref == 'refs/heads/develop'
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./studio  # Copia seus arquivos estáticos diretamente
          destination_dir: dev   # Joga tudo para a subpasta /dev no Github Pages
          keep_files: true       # Impede que apague os arquivos da raiz